version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    networks:
      - backend

  client1:
    build:
      context: .
      dockerfile: Client.Dockerfile
    depends_on:
      server:
        condition: service_started
    environment:
      - 1=Cliente1
      - 2=client1
      - 3=server
      - 4=1099
      - 5=/resources
    networks:
      - backend

  client2:
    build:
      context: .
      dockerfile: Client.Dockerfile
    depends_on:
      server:
        condition: service_started
    environment:
      - USERNAME=Cliente2
      - 2=client2
      - 3=server
      - 4=1099
      - 5=/resources
    networks:
      - backend

networks:
  backend: {}
